language: java
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - oracle-java8-installer
script: $TRAVIS_BUILD_DIR/travis/build.sh
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
env:
  global:
  - secure: cVBWCUnv/cLffMZdow03blBcsuT3PCyeIU1iDYdjSIHj2eGppnzO7akiTC4fae+56y60KwzCyNhofuHM2JEKsV86rMhQoi3LlOUnUeiWZaFgRAOTuerTeMTWllkRRQNb8R7FgxQmdnzw71FM0T341OudubrxX9t+MrLdejs6qNO07nUhxA/L8lBheWPoIjMFyr5ZHmsOWWfB6zBQ9yDR9OSWIbgsVbl/o3kWhrfjP+/OG5ATDGUWC3HtmNpMFfqSbEMsTfiVSBL8uTwOldNnrnYxMUBqnw7xMma+1vX9B/l1iGm4w44Un5RwS0FBWdjdKv7BsoUn5lRe938SquSYCDDRegskGoaXeZ+CuT36NVRqd2FA9eu5qnv6H6uvk6hh5+Hck/r+OlBvG2Jb6yRLeyUTyq8ekmEZrJH1Y5IAjdp+H25AHnULlZ6OTPUSFSPI7uTcC5RInnVem5791S+/y3VzzcEzxEpodDDno6QKt4SOJiKHO7Ssgm2aDxmcGk+oOmwDBn0I8lxRmlvzlcC/ZlXtU1ZqysFuj6YAjglsB+91JwQ0NC6Fs9C4Gggn4v2T2QSMVDFRdJs/6XPTNuJS4QL8FvYNhA7PrEluzjJ3FqYKb5l/FCYRkhjC5IZCyD8ng34lMiiia36PJiBnj2UhDrqMxjendTMdpWW32QcpVW4=
  - secure: bPaYW2xw2pLmZ5WREWM+3HSHarFhBAtRGj7Dice9H6YUahS2Bfk1nFY/jQgtVBjGJ+PSDO/GlR+XBFieeDxOoH/ls/UenvCheVuAzK4csHg+78xVOP3svg3FJtVPbaT73/of8nIVxjKxZMGKJPpnSxvEBfut5LpLvfe3AT6nDc4/rxSNjMOEzLBASYaWSvA4fbNkw57zwvWg4/2vs8/ZVLbRc4cAniGPenJ3j05WNmSx5wk93fipDzdFn25sxk/TqEhObxHkUe7rp3PHUmg8CEgxeihIL8/86jBpgcLzgzI+fk9RgB05usKmnGXsJTMlXZPoAr7ZK5FHUUl32yYx4cEjK1M4LB9QVJj1tjcLEz+/gAFeNDrw7Zlyy+TaSfhm+Vb9jiqOz8fxAnEfW8eBZeDx6FH7K0Fv9BGJAziPVQmX52Ujwmw6n1dQecWA9iV5rjCxZaf2SkdQJcM3GHZFKCp7okIfv7vdMsTfVQ9Rcl6An4zXCpXtLBAkuuJUFrxTyK4FNnh3/rXkv2Zh7WHHEHlp2BtABU/D/C2C/MOpFfhx522MEFQm1L4vFHPB+DuDqhH8g5/2vCHnzYdjEmIO8QrDQDeMp9BHO/X5NfS23sQi3RXjA3C1fsOmhazFTAL5lY9Gm+Fo7FUbeyuZGf+20BHt/yY1xL38aZ9tZF+aIhA=
